#+title: Readme

*Grupp:* =C4=

*Närvaro:* 9 - 1 - 0
| Närvarande | Frånvarande | Framtida tillfällen |
|          3 |           0 |                   7 |

*Seminarierlärare*: Olof Sisask [[mailto:olof.sisask@math.su.se][olof.sisask@math.su.se]]
*Träff:* Tisdagar 14:30 - 16:00

Namge filer på formatet ~Bastas_Alg<uppgift>V<version>.pdf~

[[https://kurser.math.su.se/mod/page/view.php?id=75166][Att skriva lösningar]]
[[https://kurser.math.su.se/mod/wwassignment/view.php?id=75115][Problemsamlingar]]
[[https://kurser.math.su.se/mod/assign/view.php?id=75171][Inlämning av uppgifter]]

* DONE Revidera uppgift 1

* DONE Skriv klart uppgift 2

* DONE Läs allmäna kommentarer
https://kurser.math.su.se/pluginfile.php/143621/mod_forum/attachment/59087/kommentarer.pdf

* TODO Skriv uppgift 3

* TODO Skriv uppgift 4

#+begin_quote
    1. Namnge din fil enligt formatet Sisask_Alg1V2.pdf, där Alg1 står för Algebra uppgift 1, och V2 står för version 2 (dvs resultatet av den första revideringen). Det kommer göra det mycket lättare att hålla saker organiserade när nya uppgifter ska lämnas in, och sedan också när analysen börjar.
    2. Undvik att börja meningar med symboler -- det kan se konstigt ut och göra flytet lite svårare att hänga med på.
    3. Prova att läsa din lösning högt -- det ska flyta på som vanligt tal. (Om ska läsa t.ex. högt så kan du helt enkelt uttala det som "x är lika med blahblahblah" för flyt-kollande-ändamål.)
#+end_quote
